apiVersion: capsule.clastix.io/v1beta2
kind: TenantResourceQuota
metadata:
  labels:
    app.kubernetes.io/name: tenantresourcequota
    app.kubernetes.io/instance: tenantresourcequota-sample
    app.kubernetes.io/part-of: capsule
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: capsule
  name: tenantresourcequota-sample
spec:
  # TODO(user): Add fields here
