---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: prometheus
  namespace: flux-system
spec:
  interval: 24h0m0s
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: flux-system
spec:
  interval: 15m
  timeout: 10m
  targetNamespace: observability-system
  releaseName: "kube-prometheus-stack"
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "61.3.2"
      sourceRef:
        kind: HelmRepository
        name: prometheus
      interval: 24h
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      remediateLastFailure: true
      retries: -1
  driftDetection:
    mode: enabled
  values:
    crds.enabled: true
    grafana:
      enabled: false
    prometheusOperator:
      enabled: true
    alertmanager:
      enabled: true
      alertmanagerSpec:
        securityContext:
          runAsGroup: 2000
          runAsNonRoot: true
          runAsUser: 1000
          fsGroup: 2000
          seccompProfile:
            type: RuntimeDefault
        containerSecurityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
        resources:
          limits:
            cpu: 300m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi

    kubeStateMetrics:
      enabled: true
    kube-state-metrics:
      securityContext:
        runAsGroup: 65534
        runAsUser: 65534
        runAsNonRoot: true
        fsGroup: 65534
        seccompProfile:
          type: RuntimeDefault
      containerSecurityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
      resources:
        limits:
          cpu: 300m
          memory: 512Mi
        requests:
          cpu: 100m
          memory: 128Mi
      prometheus:
        monitor:
          metricRelabelings:
            - action: keep
              regex: .*system.*|argocd|cert-manager|external-dns|ingress-controllers|kube-node-lease|kube-public
              sourceLabels:
                - namespace
      rbac:
        extraRules:
          - apiGroups:
            - "capsule.clastix.io"
            resources:
            - "tenants"
            verbs:
            - "list"
            - "watch"
