name: e2e
permissions: {}

on:
  push:
    branches: [ "*" ]
    paths:
      - '.github/workflows/e2e.yml'
      - 'api/**'
      - 'controllers/**'
      - 'pkg/**'
      - 'e2e/*'
      - 'Dockerfile'
      - 'go.*'
      - 'main.go'
      - 'Makefile'
  pull_request:
    branches: [ "*" ]
    paths:
      - '.github/workflows/e2e.yml'
      - 'api/**'
      - 'controllers/**'
      - 'pkg/**'
      - 'e2e/*'
      - 'Dockerfile'
      - 'go.*'
      - 'main.go'
      - 'Makefile'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  kind:
    name: Kubernetes
    strategy:
      fail-fast: false
      matrix:
        k8s-version: [ 'v1.22.4', 'v1.23.6', 'v1.24.7', 'v1.25.3', 'v1.26.3', 'v1.27.2', 'v1.28.0', 'v1.29.0']
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
        with:
          fetch-depth: 0
      - uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version-file: 'go.mod'
      - uses: engineerd/setup-kind@aa272fe2a7309878ffc2a81c56cfe3ef108ae7d0 # v0.5.0
        with:
          skipClusterCreation: true
          version: v0.14.0
      - uses: azure/setup-helm@fe7b79cd5ee1e45176fcad797de68ecaf3ca4814 # v3
        with:
          version: v3.14.2
      - name: e2e testing
        run: make e2e/${{ matrix.k8s-version }}
