name: seccomp
permissions: {}

on:
  pull_request:
    branches:
      - "*"
    paths:
      - '.github/workflows/e2e.yml'
      - 'api/**'
      - 'controllers/**'
      - 'pkg/**'
      - 'e2e/*'
      - '.ko.yaml'
      - 'Dockerfile.tracing'
      - 'go.*'
      - 'main.go'
      - 'Makefile'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  seccomp-generation:
    name: Seccomp Generation
    strategy:
      fail-fast: false
      matrix:
        k8s-version:
          - "v1.30.0"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      - uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
        with:
          go-version-file: 'go.mod'
      - uses: azure/setup-helm@fe7b79cd5ee1e45176fcad797de68ecaf3ca4814 # v4
        with:
          version: v3.14.2
      - name: unit tracing
        run: sudo make trace-unit
      - name: e2e tracing
        run: sudo KIND_K8S_VERSION=${{ matrix.k8s-version }} make trace-e2e
      - name: build seccomp profile
        run: make seccomp
      - name: upload artifact
        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
        with:
          name: capsule-seccomp
          path: capsule-seccomp.json
